### ISSUE TITLE
Execute content model in Drupal and add to module

### ISSUE THREAD

**Issue by notS0Solo** [notS0Solo/API-Migration-SWAPI#17]
_As a developer, I want to execute the content model in Drupal, so that the API data migration has a destination._

---

## Tasks
1. Create Content types, Vocabularies, etc. to match the content model documentation.
1. Export the configuration to your site's sync directory.
1. Copy the configuration files related to the content model into the custom module's config/install directory.
    - Remember to remove the UUID from the files.
1. Verify your module installs on a Drupal site and the content model configuration is imported.

## Resources
- [Managing your site's configuration (Drupal.org)](https://www.drupal.org/docs/administering-a-drupal-site/configuration-management/managing-your-sites-configuration)
   - [Overview of the Configuration System (Drupalize.me)](https://drupalize.me/tutorial/overview-configuration-system?p=2478)
   - [Configuration Management in Drupal for Beginners / DrupalCon Global 2020 (YouTube)](https://youtu.be/S9GLT4ssj2Q?si=yq3oUNK6xqZJRKFX)
- [Include default configuration in your Drupal module](https://www.drupal.org/node/2087879)
- Example module: [Pokéapi module](https://www.drupal.org/project/pokeapi)
    - This module doesn’t use migrations to import the data, but it is an example of default content model installation.

**Comment by notS0Solo** [comment]
## Next steps

- Do a database dump before starting on this. Check class notes. 
- Start creating content types, Vocabularies, etc

**Comment by notS0Solo** [comment]
I created a database backup. Then started on creating Content Types. I Created the People and Films Content Types. Created the fields as well. Though they may need tweaking. Will pick up on this tomorrow with the Planets Content Type and it's Fields.

**Comment by notS0Solo** [comment]
- Exported config files. 
- Removed UUID tags. 
- Created a pull request. 
- Created separate testing site. 

Next steps

- Compare dev/test sites
- Send for review.

**Comment by weekbeforenext** [comment]
It's looking good. We just need to sharpen it up a bit.

I submitted a review of the Pull Request (PR) for the People content type. Please don't resolve comments so I can verify the fixes on my next review.

To make changes, I suggest you:
1. Start a new DDEV site
2. Clone this module project into the modules directory
3. Install the module
4. Review each comment in the PR
    - This GitHub documentation might be helpful in seeing all of the comments: [Discovering and navigating conversations](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/about-pull-request-reviews#discovering-and-navigating-conversations)
6. Fix in Drupal
7. Export the configuration to the site sync directory
8. Copy the configuration files that have comments in the Pull Request to the module's config/install directory
9. Commit your changes to your feature branch and send this issue back to me for review.

Remember to document your changes, questions (if any), and next steps, such as "Ready for review." in a comment when you pass it back to me.

**Comment by notS0Solo** [comment]
I made the changes. There was a file(core.extension.yml) that had mistakenly been copied into the config/install directory. It was preventing the module from installing. Through some slight trial and error the file was deleted, and the changes pushed to the feature branch. Then I successfully installed the module on a new test site. So this should be Ready for Review

**Comment by weekbeforenext** [comment]
The module now installs (Yay!). The first thing I noticed is that there are two "People" content types. This likely happened because you worked from the original site where the machine name was "title" and now things are weird.

It was a while ago, but I remember we updated the machine name for People manually when we first copied the config files to the module. Working from the original site, it looks like those configuration files were added to the module in your last chages.

![Image](https://github.com/notS0Solo/swapimigration/assets/1434979/cd2b1223-e613-4436-ae27-821b98801cde)

I recommend the following as the next steps:
1. clone the module to a new site
2. check out the feature branch
3. remove configuration files in config/install that include "node.title" in the file names (I added comments to the pull request noting which files should be removed)
4. Install the module
5. Make any necessary changes to the remaining "People" content type (I think the content type description needs an update to match the others)
6. Export site configuration
7. Copy "node.people" related configuration files to the module's config/install directory
8. Remove any uuids from the files copied
9. Commit the changes
10. Push to GitHub
11. Test installing on a new site
12. Verify content types are configured as expected

**Comment by notS0Solo** [comment]
Okay. I believe finally, everything is good to go. Changes have been pushed to GitHub. I've tested installing on a new site. And I've verified the changes I made were applied. So I believe this is ready for review now

**Comment by weekbeforenext** [comment]
Completed my review and left comments on the Pull Request. Let me know if you have any questions about any of the comments.

## Next steps

- Review comments, make changes, and return for review.

**Comment by weekbeforenext** [comment]
I left just a couple of comments on the PR. This looks really good. Just a couple of fairly "simple" changes to wrap this up. 

You can probably fix the help text issue in the config file itself and not have to do the exporting and copying again. The other change is just to remove some lines from config files that are specific to exported configuration that we don't want in the module config files.

## Next steps
* Review PR comments to:
  * Add a period to the help text for the "Eye Color" field on the "People" content type.
  * Remove "_config" and "default_config_hash" lines from all config/install files.
* Pass it over for one final quick look, approval, and merge.

**Comment by weekbeforenext** [comment]
I left 3 comments that should be fairly easy fixes to the config files and this should be ready to merge. 🎉

**Comment by weekbeforenext** [comment]
Merged the PR. 🎉
